# Generated by Django 4.0.3 on 2022-05-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_player_tournament_tournamentstage_playerscore'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
