# Generated by Django 4.0.3 on 2022-05-01 16:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_playerscore_is_final'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tournamentstage',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
    ]
