# Generated by Django 4.0.3 on 2022-04-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_tournamentstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='fantasy.player')),
                ('tournament_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='fantasy.tournamentstage')),
            ],
        ),
    ]
