# Generated by Django 4.0.3 on 2022-05-03 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_alter_tournamentstage_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_c', to='fantasy.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_p2', to='fantasy.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_p3', to='fantasy.player')),
                ('tournament_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='fantasy.tournamentstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
