# Generated by Django 4.0.3 on 2022-05-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_alter_customuser_managers'),
        ('fantasy', '0006_alter_tournamentstage_managers'),
    ]

    operations = [
    ]
